### ISSUE TITLE
Unable to import C&C Renegade maps with Textures into Blender

### ISSUE THREAD

**Issue by dailafing** [OpenSAGE/OpenSAGE.BlenderPlugin#10]
I installed the plug in correctly, and I decided to import C&C City.mix (mp_city.w3d).
While the mesh imported just fine, the only textures that were loaded were the surrounding backdrop city sky scrapers.

I checked the console, see attachment
![blender w3d import issue](https://user-images.githubusercontent.com/58471820/70051878-e30b4d80-15c9-11ea-95bb-ead65947a9fc.png)

**Comment by Tarcontar** [comment]
Fixed with #11
