### ISSUE TITLE
Fail to load model with missing textures

### ISSUE THREAD

**Issue by feliwir** [OpenSAGE/OpenSAGE.BlenderPlugin#2]
Only happens for normal mapped materials. E.g.
![image](https://user-images.githubusercontent.com/2104576/63223837-c8989a00-c1bb-11e9-9f62-08bf702372b4.png)

But it should be like this:
![image](https://user-images.githubusercontent.com/2104576/63223841-d2220200-c1bb-11e9-8943-934ef4f4d5e6.png)

**Comment by Tarcontar** [comment]
Fixed with 6dea6eeb8e3dee0200836a5cca2e0d59483ba994
