### ISSUE TITLE
Exported w3d model crashes BfME 2 SDK W3D Viewer

### ISSUE THREAD

**Issue by MattTheLegoman** [OpenSAGE/OpenSAGE.BlenderPlugin#21]
I export the model and open the w3d file in the W3D Viewer from the BfME 2 SDK. The viewer crashes.
The model is pink (material issue) in World Builder.

The model is a cliff from CnC4.

[RB Rock Cliff 01.zip](https://github.com/OpenSAGE/OpenSAGE.BlenderPlugin/files/4030119/RB.Rock.Cliff.01.zip)

**Comment by Tarcontar** [comment]
fixed with #26
