### ISSUE TITLE
"Python: Traceback" issue while trying to export to w3d format on blender.

### ISSUE THREAD

**Issue by Darkry1000** [OpenSAGE/OpenSAGE.BlenderPlugin#225]
![Python Issue-01](https://user-images.githubusercontent.com/87504245/125869940-c064a84d-1d4f-475d-9382-ce5938315483.png)
![Python Issue-02](https://user-images.githubusercontent.com/87504245/125869948-a65da54a-7667-4606-b0f7-b44b04e137ad.png)

As you can see in the images, everytime i try to export to w3d, the process fails and blender show up this info log. It was not happening and i don't know what to do. Can someone please help me?

**Comment by Tarcontar** [comment]
Hi, it looks like at least one of the meshes you try to export does not have even a single vertex.

**Comment by Darkry1000** [comment]
Ok, i'll check it out! Thanks the reply Tarcontar! If i manage to solve this i'll close this issue.
