### ISSUE TITLE
Zooming in or out results in object increasing size in Command and Conquer Generals

### ISSUE THREAD

**Issue by pablodalma93** [OpenSAGE/OpenSAGE.BlenderPlugin#242]
This is a very weird effect so I had to check it several times, any zoom in or zoom out I do in Blender results in the object increasing size
in Command and Conquer: Generals. It's always increase no matter if the zoom is in or out.

**Comment by Tarcontar** [comment]
Please make sure you applied all transormations before you export the model. Please refere to https://github.com/OpenSAGE/OpenSAGE.BlenderPlugin/wiki/Troubleshooting
