### ISSUE TITLE
W3D Import always creates a "Basic_Sphere" mesh that needs to be deleted manually

### ISSUE THREAD

**Issue by xezon** [OpenSAGE/OpenSAGE.BlenderPlugin#252]
W3D Import always creates a "Basic_Sphere" mesh that needs to be deleted manually. Otherwise it does end up in a W3D export, but will not be visible.

It would be good if the Importer would not do that.

![Basic_Sphere](https://github.com/OpenSAGE/OpenSAGE.BlenderPlugin/assets/4720891/660b1861-2a00-4352-be70-7f9ed470ca92)

**Comment by xezon** [comment]
Objects list can be accessed via

![objectslist](https://github.com/OpenSAGE/OpenSAGE.BlenderPlugin/assets/4720891/54e03d7b-5cbe-4331-859f-964e6cc26ebb)

**Comment by Tarcontar** [comment]
will be fixed with the next release
