### ISSUE TITLE
Test: Import and export, compare binary

### ISSUE THREAD

**Issue by xezon** [OpenSAGE/OpenSAGE.BlenderPlugin#258]
Right now we see discrepancies when importing and exporting W3D files with the Blender Plugin. Would it be possible to setup a test for the Blender Plugin to mass import and export w3d files and compare the new export with the original and then highlight the discrepancies? This way we could see where the Blender Plugins produces wrong results, either on import or export.

jonwil says:
> I can tell you that if you export a w3d file multiple times in a row from the same it will produce the same output. At least with the max plugins (EAs or mine).

**Comment by Michaelschnabel-DM** [comment]
Right now it is not possible to persist all data inside the w3d files one to one during a blender import and export workflow. This is caused by the fact that not everything inside the w3d files can be represented with the featureset of blender.

**Comment by Michaelschnabel-DM** [comment]
Most likely this state will never reached. 3D Max is basically the same as GMax/RenX under the hood in that regard. Thats why adapting all the material and shading stuff is pretty much straight forward. But for blender a lot of that stuff (even basics like the armatures) had to be adapted to the way things are handled in blender (which can be quite different from w3d) and thus a complete roundtrip of a file where the same binary result will be generated as the input file will most likely never be possible.
