### ISSUE TITLE
Blender 4.1+ fails to import mesh due to `mesh.use_auto_smooth` no longer being a thing

### ISSUE THREAD

**Issue by cyberarm** [OpenSAGE/OpenSAGE.BlenderPlugin#266]
https://github.com/OpenSAGE/OpenSAGE.BlenderPlugin/blob/1c3bf3516d85bcd7b78245d103b2f73c97581088/io_mesh_w3d/common/utils/mesh_import.py#L26

**Comment by Tarcontar** [comment]
fixed by #267
