### ISSUE TITLE
hierarchy and mesh/object with same name

### ISSUE THREAD

**Issue by feliwir** [OpenSAGE/OpenSAGE.BlenderPlugin#3]
Fixes the loading of animations for structures. Sometimes the skeleton is inside the model itself

**Comment by Tarcontar** [comment]
The problem here is, that in some cases the Hierarchy and a Mesh are in the same file. Also both are named the same way, so we can not construct each of them with this name. Tried to create them in separate collections, but that doesn' t work.

**Comment by Tarcontar** [comment]
For now append ".skl" to the skeleton/hierarchy as a workaround until a better solution is found.

**Comment by Tarcontar** [comment]
-> do not create skeletons for those files and fix the error when no skeleton is found fce23b95bc0d3a4792682baa4f67837a2ff614f7

**Comment by Tarcontar** [comment]
not creating a skeleton causes issues with other specific files, which not only contain "non bone pivots" but also regular valid pivots. In this case we need to create a skeleton, but can not name it the same way as the mesh…

**Comment by Tarcontar** [comment]
reintroduced workaround with appending "SKL" to the armature since blender does not support a better solution for now. ddf6ddf953f83e97ece52593ff0c1fd5434e97be
