### ISSUE TITLE
Support dazzle chunk type

### ISSUE THREAD

**Issue by feliwir** [OpenSAGE/OpenSAGE.BlenderPlugin#8]
Used for some vehicles in renegade as a mesh type. It's used e.g. for front lights and stuff like this. There are multiple dazzle types aswell which we must provide a dropdown list for in blender.

It would maybe make sense to put all the different geometry types (see image below) into one property setting.
![grafik](https://user-images.githubusercontent.com/2104576/69579282-7fce5980-0fd2-11ea-84f9-8486a8d952c9.png)

**Comment by Tarcontar** [comment]
Implemented with #16
