### ISSUE TITLE
Support multiple levels of details

### ISSUE THREAD

**Issue by feliwir** [OpenSAGE/OpenSAGE.BlenderPlugin#9]
Right now we only support 1 level of detail (LOD) in our plugin since BFME rarely uses more LODs. However for C&C Renegade (and possible other parts of the series) this is not the case. I suggest creating a collection during import stage when a mesh has multiple LODs e.g. like this:
![grafik](https://user-images.githubusercontent.com/2104576/69578397-b3a87f80-0fd0-11ea-9677-3f4ba1c5aa56.png)

During export there should be an option to select the number of levels (defaulting with the levels found at import). In case a mesh has no low poly version we can easily generate one with Blender.

Part of this issue is that we must connect Hierarchy and the HLod with the `BoneIndex` instead of the `BoneName`

**Comment by Tarcontar** [comment]
fixed with #19
